# Generated by Django 3.0.5 on 2020-04-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=50)),
                ('phn', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
